name: Build OnePlus-Sm8150-Kernel-LOS20
on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KERNEL_DEFCONFIG: "vendor/sm8150-perf_defconfig"
      KERNEL_CMDLINE: "ARCH=arm64 CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-androidkernel- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1 CONFIG_BUILD_ARM64_DT_OVERLAY=n O=out"
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt install gcc-aarch64-linux-gnu -y
        sudo apt install gcc-arm-linux-gnueabi -y
        sudo apt install binutils make python3 libssl-dev build-essential bc  bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs -y
        git clone https://github.com/grm34/proton-clang -b ZenMaxBuilder clang
        git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 aarch64
        git clone https://github.com/snowwolf725/AnyKernel3 -b oneplus7 --depth=1
        rm -rf AnyKernel3/.git

    - name: Build Kernel
      run: |
       export PATH=$(pwd)/clang/bin/:$(pwd)/aarch64/bin/:$PATH
       export ARCH=arm64
       export SUBARCH=arm64
       export LD=ld.lld
       export BRAND_SHOW_FLAG=oneplus
       export TARGET_PRODUCT=msmnile
       make $KERNEL_CMDLINE $KERNEL_DEFCONFIG CC=clang
       make $KERNEL_CMDLINE CC=clang -j$(nproc --all)
       cp out/arch/arm64/boot/Image AnyKernel3
    - name: Upload Kernel-SU
      uses: actions/upload-artifact@v3
      with:
        name: OP7-LOS20-kernel-SU
        path: "AnyKernel3/*"
